require('scripts/mouse')

local cursorNormal = {
  "X                               ",
  "XX                              ",
  "X.X                             ",
  "X..X                            ",
  "X...X                           ",
  "X....X                          ",
  "X.....X                         ",
  "X......X                        ",
  "X.......X                       ",
  "X........X                      ",
  "X.....XXXXX                     ",
  "X..X..X                         ",
  "X.X X..X                        ",
  "XX  X..X                        ",
  "X    X..X                       ",
  "     X..X                       ",
  "      X..X                      ",
  "      X..X                      ",
  "       XX                       ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
}

local cursorVertical = {
"                                ",
"                                ",
"                                ",
"               X                ",
"              X.X               ",
"             X...X              ",
"            X.....X             ",
"           X.......X            ",
"          XXXXX.XXXXX           ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"              X.X               ",
"          XXXXX.XXXXX           ",
"           X.......X            ",
"            X.....X             ",
"             X...X              ",
"              X.X               ",
"               X                ",
"                                ",
"                                ",
"                                ",
}

local cursorHorizontal = {
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"        X               X       ",
"       XX               XX      ",
"      X.X               X.X     ",
"     X..X               X..X    ",
"    X...XXXXXXXXXXXXXXXXX...X   ",
"   X.........................X  ",
"    X...XXXXXXXXXXXXXXXXX...X   ",
"     X..X               X..X    ",
"      X.X               X.X     ",
"       XX               XX      ",
"        X               X       ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
}

local cursorDiagonal1 = {
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"       XXXXXXXX                 ",
"       X.....X                  ",
"       X....X                   ",
"       X...X                    ",
"       X..X.X                   ",
"       X.X X.X                  ",
"       XX   X.X                 ",
"       X     X.X                ",
"              X.X               ",
"               X.X              ",
"                X.X             ",
"                 X.X     X      ",
"                  X.X   XX      ",
"                   X.X X.X      ",
"                    X.X..X      ",
"                     X...X      ",
"                    X....X      ",
"                   X.....X      ",
"                  XXXXXXXX      ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
}

local cursorDiagonal2 = {
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                 XXXXXXXX       ",
"                  X.....X       ",
"                   X....X       ",
"                    X...X       ",
"                   X.X..X       ",
"                  X.X X.X       ",
"                 X.X   XX       ",
"                X.X     X       ",
"               X.X              ",
"              X.X               ",
"             X.X                ",
"      X     X.X                 ",
"      XX   X.X                  ",
"      X.X X.X                   ",
"      X..X.X                    ",
"      X...X                     ",
"      X....X                    ",
"      X.....X                   ",
"      XXXXXXXX                  ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
}

function prepareCursors()
	loadCursor("normal",32,32,0,0,cursorNormal)
	loadCursor("vertical",32,32,16,16,cursorVertical)
	loadCursor("horizontal",32,32,16,16,cursorHorizontal)
	loadCursor("diagonal1",32,32,16,16,cursorDiagonal1)
	loadCursor("diagonal2",32,32,16,16,cursorDiagonal2)
end